"""updated climate measure table definition and created affiliate table

Revision ID: 0c5ab70ef25b
Revises: 
Create Date: 2022-10-11 20:01:10.395952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5ab70ef25b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('promoCode', sa.String(), nullable=False),
                    sa.Column('organizationName', sa.String(), nullable=True),
                    sa.Column('emailAddress', sa.String(), nullable=True),
                    sa.Column('totalCarsOffRoad', sa.Float(), nullable=True),
                    sa.Column('totalFightingFoodWaste', sa.Float(), nullable=True),
                    sa.Column('totalWaterSaved', sa.Float(), nullable=True),
                    sa.Column('totalLandUse', sa.Float(), nullable=True),
                    sa.Column('totalCholesterolSaved', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('promoCode'),
                    schema='CCC'
                    )
    op.create_table('climate_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('carsOffRoad', sa.Float(), nullable=True),
    sa.Column('fightingFoodWaste', sa.Float(), nullable=True),
    sa.Column('waterSaved', sa.Float(), nullable=True),
    sa.Column('landUse', sa.Float(), nullable=True),
    sa.Column('cholesterolSaved', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='CCC'
    )
    op.create_index(op.f('ix_CCC_climate_measure_id'), 'climate_measure', ['id'], unique=False, schema='CCC')
    op.create_index(op.f('ix_CCC_climate_measure_sku'), 'climate_measure', ['sku'], unique=False, schema='CCC')
    op.create_table('climate_measure_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=True),
    sa.Column('lastModifiedDateTime', sa.DateTime(), nullable=True),
    sa.Column('lastModifiedBy', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='CCC'
    )
    op.create_index(op.f('ix_CCC_climate_measure_audit_id'), 'climate_measure_audit', ['id'], unique=False, schema='CCC')
    op.create_index(op.f('ix_CCC_climate_measure_audit_sku'), 'climate_measure_audit', ['sku'], unique=False, schema='CCC')
    op.create_table('affiliate_climate_change_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promoCode', sa.String(), nullable=False),
    sa.Column('totalCarsOffRoad', sa.Float(), nullable=True),
    sa.Column('totalFightingFoodWaste', sa.Float(), nullable=True),
    sa.Column('totalWaterSaved', sa.Float(), nullable=True),
    sa.Column('totalLandUse', sa.Float(), nullable=True),
    sa.Column('totalCholesterolSaved', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['promoCode'], ['CCC.affiliate.promoCode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promoCode'),
    schema='CCC'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliate_climate_change_impact', schema='CCC')
    op.drop_index(op.f('ix_CCC_climate_measure_audit_sku'), table_name='climate_measure_audit', schema='CCC')
    op.drop_index(op.f('ix_CCC_climate_measure_audit_id'), table_name='climate_measure_audit', schema='CCC')
    op.drop_table('climate_measure_audit', schema='CCC')
    op.drop_index(op.f('ix_CCC_climate_measure_sku'), table_name='climate_measure', schema='CCC')
    op.drop_index(op.f('ix_CCC_climate_measure_id'), table_name='climate_measure', schema='CCC')
    op.drop_table('climate_measure', schema='CCC')
    op.drop_table('affiliate', schema='CCC')
    # ### end Alembic commands ###
